#!/usr/bin/python
# -*- coding: utf-8 -*-

# plugins.json was generated by command:
# curl -kLsS "https:/<jenkins>/pluginManager/api/json?pretty=1&tree=plugins\[shortName,longName,version\]"

import sys
import json

with open("./plugins.json", 'r') as load_f:
    l_obj = json.load(load_f)
    print(l_obj)

plugins = l_obj["plugins"]

for item in plugins:
    longname = item["longName"]
    shortname = item["shortName"]
    version = item["version"]
    print("%s:%s" % (shortname, version))
